# Generated by Django 5.2 on 2025-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('des', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('close', 'close')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
