# Generated by Django 5.2 on 2025-05-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])),
                ('read_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('passing_year', models.IntegerField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('obt_marks', models.PositiveIntegerField(default=100)),
                ('per', models.FloatField(default=0.0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.student')),
            ],
        ),
    ]
